#!/bin/sh

# if app not exist
if [ ! -f /bin/wscd ]; then
    exit 0
fi

# get params
. /etc/scripts/global.sh

LOG="logger -t wscd"

start() {
    get_param
    if [ "$WscModeOption" != "" ] || [ "$WscModeOption" != "0" ]; then
      $LOG "Starting WPS"
	ip -4 route replace 239.255.255.250 dev br0 > /dev/null 2>&1
	if [ "$OperationMode" = "0" ] || [ "$ApCliBridgeOnly" = "1" ]; then
	    wscd -m 1 -a $lan_ipaddr -i $first_wlan_root_if -D &
	else
	    wscd -m 1 -i $first_wlan_root_if -D &
	fi
    fi
}

stop() {
    pid=`pidof wscd`
    if [ "$pid" != "" ]; then
	$LOG "Stopping WPS"
	killall -q wscd
	killall -q -SIGKILL wscd
    fi
}

get_param() {
    eval `nvram_buf_get 2860 WscModeOption lan_ipaddr`
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
