#!/bin/sh

ROOTDIR=`pwd`
export ROOTDIR=$ROOTDIR
ln -sf linux-2.6.21.x linux

echo "-------------REMOVE_IMAGES---------------"
rm -rf $ROOTDIR/images
if [ "$1" != "RELEASE" ]; then
    rm -rf $ROOTDIR/releases
fi

echo "------------FULL_DISTCLEAN---------------"
make clean
rm -f linux

echo "-------------RESTORE_DIRS----------------"
mkdir -p $ROOTDIR/releases
mkdir -p $ROOTDIR/images
